#!/usr/bin/env bash
#Bash script that displays the time for 12 hours and 59 minutes.
hour=0
while [ $hour -le 12 ]; do
min=0
while [ $min -lt 60 ]; do
printf "Hour: %02d:%02d\n" $hour $min
((min++))
done
((hour++))
done
