#!/usr/bin/env bash
# Bash script that gives you information about a school file.

while true; do
    read -p "Enter the path to the school file: " school

    if [ -e "$school" ]; then
        echo "School file exists"

        if [ -s "$school" ]; then
            echo "School file is not empty"
        else
            echo "School file is empty"
        fi

        if [ -f "$school" ]; then
            echo "School is a regular file"
        fi

        break  # Exit the loop if the file exists
    else
        echo "School file does not exist"
    fi
done

