#!/usr/bin/env bash
# Bash script to connect to a server without typing a password
Host 54.144.87.36
    HostName 54.144.87.36
    User ubuntu
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
